### ISSUE TITLE
Consider Adding QuestTrade as alternative to TradeKing for Canadians [feature]

### ISSUE THREAD

**Issue by richjdsmith** [maxbbraun/trump2cash#19]
Their API docs are here: http://www.questrade.com/api/documentation/getting-started

I am very new to coding but will give it a shot. May need someone with better code eyes to review.

**Comment by interwho** [comment]
@richjdsmith Want to work together on this?

**Comment by interwho** [comment]
I forked this and added support for Questrade, however, I had to rip out support for TradeKing as a result since things were too tightly integrated, and Questrade's API is missing a bunch of features that TradeKing's has.

See: https://github.com/interwho/trump2cash

I suppose trading.py can be modularized further to support both, with the user being able to choose which to use.

**Comment by maxbbraun** [comment]
Consolidating into #22.
