### ISSUE TITLE
Decreasing return

### ISSUE THREAD

**Issue by domingohui** [maxbbraun/trump2cash#47]
I notice ```benchmark.md``` hasn't been updated lately. But I'm just curious why the algorithm is not as effective after January. Is it because of the accuracy of the sentiment analysis or the correlation between share prices and trump's tweets has gone down? Could also be taking too much risk? But that's hard to tell w/o looking at the sentiment scores...

**Comment by moe-khan123** [comment]
By skimming through the code, I believe if its a positive sentiment / bull market -- Stock is bought then sold at the end of the day. It's not very complex since by the end of the day at market close, it is very possible that the market had rallied back down a bit and there is not an optimal return. 

I think we should definitely use buying volume/selling volume data into the equation so that we can get top return. Then again, not much of a quant or algorithmic trader expert :P Thoughts?

**Comment by WilliamJamesDalrympleWest** [comment]
How did you get on with this\/

**Comment by maxbbraun** [comment]
See #54.
